name: co2_dash
channels:
  - pyviz
  - conda-forge
  - pip
  - defaults
dependencies:
  - bokeh=2.4.3
  - fiona=1.9.3
  - folium=0.14.0
  - gdal=3.6.4
  - geopandas=0.12.2
  - geopandas-base=0.12.2
  - holoviews=1.15.4
  - hvplot=0.8.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - libgdal=3.6.4
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbformat=5.7.0
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - numpy=1.24.3
  - pandas=2.0.0
  - panel=0.14.4
  - param=1.13.0
  - pip=23.0.1
  - python=3.9.16
  - pip:
    - jupyter-panel-proxy==0.1.0
    - jupyter-server-proxy==4.0.0
